import os
import json
from openai import OpenAI


client = OpenAI(api_key=os.environ.get("LLM_trainer"))


def describe_workout_plan(plan_data: dict) -> str:
    prompt = f"""
You are a professional fitness trainer assistant.

Below you will receive a structured workout plan generated by a rule-based recommendation system.

Your task:
- Explain the workout plan in clear and natural language.
- Write in English.
- Do NOT write in markdown.
- Describe each training day separately.
- Do NOT change the exercises.
- Do NOT change the number of sets or reps.
- Do NOT invent additional exercises.
- Do NOT use more than 2000 characters
- make each day paragaph start with: ### Day [number] : [day_name]
- for each day: list all the exercises in this format: [exercise]: - [sets] x [reps] reps and [rest]s of rest
and then short description of the exercise and its purpose. Make it one exercise per line.
- if workout plan in JSON contains warnings, comment them at the end and mention they are due to lack of equipment

Workout plan JSON:
{json.dumps(plan_data, indent=2)}
"""

    response = client.responses.create(
        model="gpt-4o",
        input=prompt,
        max_output_tokens=4000
    )

    return response.output_text