import os
import json
from openai import OpenAI


client = OpenAI(api_key=os.environ.get("LLM_trainer"))


def describe_workout_plan(plan_data: dict) -> str:
    prompt = f"""
You are a professional fitness trainer assistant.

Below you will receive a structured workout plan generated by a rule-based recommendation system.

Your task:
- Explain the workout plan in clear and natural language.
- Write in English.
- Do NOT write in markdown.
- Describe each training day separately.
- Briefly explain why this split makes sense for the user.
- Add practical tips about rest time, exercise execution, and recovery.
- Do NOT change the exercises.
- Do NOT change the number of sets or reps.
- Do NOT invent additional exercises.
- Do NOT use more than 2000 characters
- describe plan day by day, make each day paragaph start with: ### Day [number] : [day_name]

Workout plan JSON:
{json.dumps(plan_data, indent=2)}
"""

    response = client.responses.create(
        model="gpt-4o",
        input=prompt,
        max_output_tokens=2000
    )

    return response.output_text